package prosper

import (
	"reflect"
	"testing"
	"time"

	"github.com/mtlynch/gofn-prosper/prosper/thin"
	"github.com/mtlynch/gofn-prosper/types"
)

func TestListingParser(t *testing.T) {
	var tests = []struct {
		input         thin.SearchResult
		want          types.Listing
		expectSuccess bool
		msg           string
	}{
		{
			input: thin.SearchResult{
				PriorProsperLoans:                         0,
				AmountDelinquent:                          0,
				AmountParticipation:                       0,
				DelinquenciesOver60Days:                   3,
				GroupIndicator:                            false,
				IncomeRange:                               3,
				ListingMonthlyPayment:                     285.46,
				OldestTradeOpenDate:                       "03221991",
				PriorProsperLoansPrincipalOutstanding:     0,
				PublicRecordsLast12Months:                 0,
				TotalOpenRevolvingAccounts:                3,
				VerificationStage:                         2,
				ListingStatus:                             2,
				ListingTitle:                              "Large Purchases",
				BorrowerListingDescription:                "",
				DelinquenciesLast7Years:                   14,
				EmploymentStatusDescription:               "Other",
				ListingStartDate:                          "2015-12-04 17:02:28 +0000",
				TotalTradeItems:                           28,
				BorrowerRate:                              0.1706,
				IsHomeowner:                               false,
				ListingAmount:                             8000,
				ListingNumber:                             4247229,
				PriorProsperLoans61dpd:                    0,
				PriorProsperLoansPrincipalBorrowed:        0,
				WasDelinquentDerog:                        5,
				BankcardUtilization:                       0.32,
				InstallmentBalance:                        0,
				InvestmentTypeid:                          1,
				ListingCategoryId:                         14,
				BorrowerCity:                              "PASADENA",
				BorrowerState:                             "MD",
				IncomeRangeDescription:                    "$25,000-49,999",
				ProsperScore:                              4,
				RevolvingAvailablePercent:                 72,
				WholeLoanStartDate:                        "",
				CurrentCreditLines:                        2,
				DtiWprosperLoan:                           0.14,
				FicoScore:                                 "660-679",
				FirstRecordedCreditLine:                   "1991-03-22 08:00:00 +0000",
				RealEstateBalance:                         0,
				SatisfactoryAccounts:                      23,
				FundingThreshold:                          0.7,
				InquiriesLast6Months:                      3,
				LenderYield:                               0.1606,
				MemberKey:                                 "AF001946468823A105AE",
				PriorProsperLoanEarliestPayOff:            0,
				PriorProsperLoansCyclesBilled:             0,
				CurrentDelinquencies:                      0,
				DelinquenciesOver30Days:                   5,
				InvestmentTypeDescription:                 "Fractional",
				ListingStatusReason:                       "Active",
				MonthlyDebt:                               144,
				MonthsEmployed:                            72,
				PartialFundingIndicator:                   true,
				ProsperRating:                             "C",
				BorrowerApr:                               0.20777,
				GroupName:                                 "",
				ListingPurpose:                            "",
				PriorProsperLoans31dpd:                    0,
				PriorProsperLoansLatePaymentsOneMonthPlus: 0,
				RealEstatePayment:                         0,
				CreditLinesLast7Years:                     28,
				CreditPullDate:                            "2015-12-04 01:03:03 +0000",
				PublicRecordsLast10Years:                  0,
				RevolvingBalance:                          978,
				Scorex:                                    "702-723",
				ScorexChange:                              "",
				BorrowerMetropolitanArea:                  "(Not Implemented)",
				MinPriorProsperLoan:                       0,
				WholeLoanEndDate:                          "",
				AmountFunded:                              833.91,
				EffectiveYield:                            0.1582,
				EstimatedLossRate:                         0.0824,
				ListingCreationDate:                       "2015-12-04 00:31:34 +0000",
				Occupation:                                "",
				PercentFunded:                             0.1042,
				PriorProsperLoansBalanceOutstanding:       0,
				AmountRemaining:                           7166.09,
				DelinquenciesOver90Days:                   14,
				ListingEndDate:                            "",
				OpenCreditLines:                           2,
				PriorProsperLoansActive:                   0,
				PriorProsperLoansLateCycles:               0,
				ListingTerm:                               36,
				PriorProsperLoansOntimePayments:           0,
				EstimatedReturn:                           0.0758,
				IncomeVerifiable:                          true,
				LenderIndicator:                           0,
				MaxPriorProsperLoan:                       0,
				NowDelinquentDerog:                        0,
				StatedMonthlyIncome:                       3000,
				TotalInquiries:                            6,
				LastUpdatedDate:                           "",
			},
			want: types.Listing{
				PriorProsperLoans:                         0,
				AmountDelinquent:                          0,
				AmountParticipation:                       0,
				DelinquenciesOver60Days:                   3,
				ListingMonthlyPayment:                     285.46,
				OldestTradeOpenDate:                       time.Date(1991, 3, 22, 0, 0, 0, 0, time.UTC),
				PriorProsperLoansPrincipalOutstanding:     0,
				PublicRecordsLast12Months:                 0,
				TotalOpenRevolvingAccounts:                3,
				VerificationStage:                         2,
				ListingStatus:                             types.ListingActive,
				ListingTitle:                              "Large Purchases",
				DelinquenciesLast7Years:                   14,
				EmploymentStatusDescription:               "Other",
				ListingCreationDate:                       time.Date(2015, 12, 4, 0, 31, 34, 0, time.UTC),
				ListingStartDate:                          time.Date(2015, 12, 4, 17, 2, 28, 0, time.UTC),
				ListingEndDate:                            time.Time{},
				TotalTradeItems:                           28,
				BorrowerRate:                              0.1706,
				IsHomeowner:                               false,
				ListingAmount:                             8000,
				ListingNumber:                             4247229,
				PriorProsperLoans61dpd:                    0,
				PriorProsperLoansPrincipalBorrowed:        0,
				WasDelinquentDerog:                        5,
				BankcardUtilization:                       0.32,
				InstallmentBalance:                        0,
				InvestmentTypeId:                          1,
				ListingCategoryId:                         14,
				BorrowerCity:                              "PASADENA",
				BorrowerState:                             "MD",
				IncomeRange:                               types.Between25kAnd50k,
				IncomeRangeDescription:                    "$25,000-49,999",
				ProsperScore:                              4,
				RevolvingAvailablePercent:                 72,
				CurrentCreditLines:                        2,
				DtiWprosperLoan:                           0.14,
				FicoScore:                                 types.Between660And679,
				FirstRecordedCreditLine:                   time.Date(1991, 3, 22, 8, 0, 0, 0, time.UTC),
				RealEstateBalance:                         0,
				SatisfactoryAccounts:                      23,
				FundingThreshold:                          0.7,
				InquiriesLast6Months:                      3,
				LenderYield:                               0.1606,
				MemberKey:                                 "AF001946468823A105AE",
				PriorProsperLoanEarliestPayOff:            0,
				PriorProsperLoansCyclesBilled:             0,
				CurrentDelinquencies:                      0,
				DelinquenciesOver30Days:                   5,
				InvestmentTypeDescription:                 "Fractional",
				ListingStatusReason:                       "Active",
				MonthlyDebt:                               144,
				MonthsEmployed:                            72,
				PartialFundingIndicator:                   true,
				ProsperRating:                             types.RatingC,
				BorrowerApr:                               0.20777,
				PriorProsperLoans31dpd:                    0,
				PriorProsperLoansLatePaymentsOneMonthPlus: 0,
				RealEstatePayment:                         0,
				CreditLinesLast7Years:                     28,
				CreditPullDate:                            time.Date(2015, 12, 4, 1, 3, 3, 0, time.UTC),
				PublicRecordsLast10Years:                  0,
				RevolvingBalance:                          978,
				ScoreX:                                    "702-723",
				ScoreXChange:                              "",
				MinPriorProsperLoan:                       0,
				AmountFunded:                              833.91,
				EffectiveYield:                            0.1582,
				EstimatedLossRate:                         0.0824,
				Occupation:                                "",
				PercentFunded:                             0.1042,
				PriorProsperLoansBalanceOutstanding:       0,
				AmountRemaining:                           7166.09,
				DelinquenciesOver90Days:                   14,
				OpenCreditLines:                           2,
				PriorProsperLoansActive:                   0,
				PriorProsperLoansLateCycles:               0,
				ListingTerm:                               36,
				PriorProsperLoansOntimePayments:           0,
				EstimatedReturn:                           0.0758,
				IncomeVerifiable:                          true,
				LenderIndicator:                           0,
				MaxPriorProsperLoan:                       0,
				NowDelinquentDerog:                        0,
				StatedMonthlyIncome:                       3000,
				TotalInquiries:                            6,
				WholeLoanStartDate:                        time.Time{},
				WholeLoanEndDate:                          time.Time{},
				LastUpdatedDate:                           time.Time{},
			},
			expectSuccess: true,
			msg:           "valid listing should parse successfully",
		},
		{
			input: thin.SearchResult{
				MemberKey:                   "A9A73458009412ECD63F",
				ListingNumber:               989367,
				CreditPullDate:              "2015-11-02 03:36:21 +0000",
				ListingStartDate:            "2015-12-31 01:12:44 +0000",
				ListingCreationDate:         "2015-11-02 03:36:20 +0000",
				ListingStatus:               2,
				ListingStatusReason:         "Active",
				VerificationStage:           1,
				ListingAmount:               20000.0,
				AmountFunded:                0.0,
				AmountRemaining:             20000.0,
				PercentFunded:               0.0,
				PartialFundingIndicator:     true,
				FundingThreshold:            0.7,
				ProsperRating:               "A",
				EstimatedReturn:             0.0431,
				EstimatedLossRate:           0.0249,
				LenderYield:                 0.0674,
				EffectiveYield:              0.068,
				BorrowerRate:                0.0774,
				BorrowerApr:                 0.10531,
				ListingTerm:                 36,
				ListingMonthlyPayment:       624.33,
				Scorex:                      "778+",
				FicoScore:                   "780-799",
				ListingCategoryId:           1,
				ListingTitle:                "Debt consolidation",
				IncomeRange:                 6,
				IncomeRangeDescription:      "$100,000+",
				StatedMonthlyIncome:         8333.33,
				IncomeVerifiable:            true,
				DtiWprosperLoan:             0.08,
				EmploymentStatusDescription: "Full-time",
				Occupation:                  "Accountant/CPA",
				MonthsEmployed:              67,
				BorrowerState:               "TX",
				BorrowerCity:                "PLAINVIEW",
				BorrowerMetropolitanArea:    "(Not Implemented)",
				PriorProsperLoansActive:     0,
				PriorProsperLoans:           0,
				LenderIndicator:             0,
				GroupIndicator:              false,
				ChannelCode:                 "40000",
				AmountParticipation:         0.0,
				MonthlyDebt:                 20.0,
				CurrentDelinquencies:        0,
				DelinquenciesLast7Years:     0,
				PublicRecordsLast10Years:    0,
				PublicRecordsLast12Months:   0,
				FirstRecordedCreditLine:     "1997-08-19 07:00:00 +0000",
				CreditLinesLast7Years:       6,
				InquiriesLast6Months:        1,
				AmountDelinquent:            0.0,
				CurrentCreditLines:          5,
				OpenCreditLines:             4,
				BankcardUtilization:         0.01,
				TotalOpenRevolvingAccounts:  4,
				RevolvingBalance:            304.0,
				RevolvingAvailablePercent:   98,
				TotalInquiries:              1,
				TotalTradeItems:             6,
				SatisfactoryAccounts:        6,
				NowDelinquentDerog:          0,
				WasDelinquentDerog:          0,
				OldestTradeOpenDate:         "08191997",
				DelinquenciesOver30Days:     0,
				DelinquenciesOver60Days:     0,
				DelinquenciesOver90Days:     0,
				InvestmentTypeid:            1,
				InvestmentTypeDescription:   "Fractional",
				WholeLoanStartDate:          "2015-11-02 21:43:59 +0000",
				WholeLoanEndDate:            "2015-11-03 00:45:04 +0000",
				IsHomeowner:                 false,
				LastUpdatedDate:             "2015-11-03 01:01:26 +0000",
			},
			want: types.Listing{
				MemberKey:                   "A9A73458009412ECD63F",
				ListingNumber:               989367,
				CreditPullDate:              time.Date(2015, 11, 2, 3, 36, 21, 0, time.UTC),
				ListingStartDate:            time.Date(2015, 12, 31, 1, 12, 44, 0, time.UTC),
				ListingCreationDate:         time.Date(2015, 11, 2, 3, 36, 20, 0, time.UTC),
				ListingStatus:               2,
				ListingStatusReason:         "Active",
				VerificationStage:           1,
				ListingAmount:               20000.0,
				AmountFunded:                0.0,
				AmountRemaining:             20000.0,
				PercentFunded:               0.0,
				PartialFundingIndicator:     true,
				FundingThreshold:            0.7,
				ProsperRating:               types.RatingA,
				EstimatedReturn:             0.0431,
				EstimatedLossRate:           0.0249,
				LenderYield:                 0.0674,
				EffectiveYield:              0.068,
				BorrowerRate:                0.0774,
				BorrowerApr:                 0.10531,
				ListingTerm:                 36,
				ListingMonthlyPayment:       624.33,
				ScoreX:                      "778+",
				FicoScore:                   types.Between780And799,
				ListingCategoryId:           1,
				ListingTitle:                "Debt consolidation",
				IncomeRange:                 types.Over100k,
				IncomeRangeDescription:      "$100,000+",
				StatedMonthlyIncome:         8333.33,
				IncomeVerifiable:            true,
				DtiWprosperLoan:             0.08,
				EmploymentStatusDescription: "Full-time",
				Occupation:                  "Accountant/CPA",
				MonthsEmployed:              67,
				BorrowerState:               "TX",
				BorrowerCity:                "PLAINVIEW",
				PriorProsperLoansActive:     0,
				PriorProsperLoans:           0,
				LenderIndicator:             0,
				AmountParticipation:         0.0,
				MonthlyDebt:                 20.0,
				CurrentDelinquencies:        0,
				DelinquenciesLast7Years:     0,
				PublicRecordsLast10Years:    0,
				PublicRecordsLast12Months:   0,
				FirstRecordedCreditLine:     time.Date(1997, 8, 19, 7, 0, 0, 0, time.UTC),
				CreditLinesLast7Years:       6,
				InquiriesLast6Months:        1,
				AmountDelinquent:            0.0,
				CurrentCreditLines:          5,
				OpenCreditLines:             4,
				BankcardUtilization:         0.01,
				TotalOpenRevolvingAccounts:  4,
				RevolvingBalance:            304.0,
				RevolvingAvailablePercent:   98,
				TotalInquiries:              1,
				TotalTradeItems:             6,
				SatisfactoryAccounts:        6,
				NowDelinquentDerog:          0,
				WasDelinquentDerog:          0,
				OldestTradeOpenDate:         time.Date(1997, 8, 19, 0, 0, 0, 0, time.UTC),
				DelinquenciesOver30Days:     0,
				DelinquenciesOver60Days:     0,
				DelinquenciesOver90Days:     0,
				InvestmentTypeId:            1,
				InvestmentTypeDescription:   "Fractional",
				WholeLoanStartDate:          time.Date(2015, 11, 2, 21, 43, 59, 0, time.UTC),
				WholeLoanEndDate:            time.Date(2015, 11, 3, 0, 45, 4, 0, time.UTC),
				IsHomeowner:                 false,
				LastUpdatedDate:             time.Date(2015, 11, 3, 1, 1, 26, 0, time.UTC),
			},
			expectSuccess: true,
			msg:           "valid listing should parse successfully",
		},
	}
	for _, tt := range tests {
		got, err := defaultListingParser{}.Parse(tt.input)
		if tt.expectSuccess && err != nil {
			t.Errorf("%s - expected successful parsing of %+v, got error: %v", tt.msg, tt.input, err)
		} else if !tt.expectSuccess && err == nil {
			t.Errorf("%s - expected failure for %+v, got nil", tt.msg, tt.input)
		}
		if tt.expectSuccess && !reflect.DeepEqual(got, tt.want) {
			t.Errorf("%s - defaulListingParser.Parse got: %#v, want: %#v", tt.msg, got, tt.want)
		}
	}
}
